version: '3'
services: 
 ui:
  container_name: ui
  build:
   context: "./ui"
   dockerfile: "Dockerfile-prod"
  volumes: 
   - "./ui/uiresource:/ang"
  labels:
   - "traefik.enable=true"
   - "traefik.http.routers.ui.rule=Host(`egozz.localhost`)"
   - "traefik.http.routers.ui.entrypoints=web"
 api:
  container_name: api
  build:
   context: "./api"
   dockerfile: "Dockerfile"
  env_file: "./credentials.env"
  ports:
   - "8055:8055"
  # restart: always
  labels:
   - "traefik.enable=true"
   - "traefik.http.routers.api.rule=Host(`api.egozz.localhost`)"
   - "traefik.http.routers.api.entrypoints=web"
 traefik:
  container_name: traefik
  image: traefik:2.1.3
  command: 
   - "--api.insecure=true"
   - "--providers.docker=true"
   - "--providers.docker.exposedbydefault=false"
   - "--entrypoints.web.address=:80"
  ports:
   - "8080:8080"
   - "80:80"
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock:ro"
  labels:
   - "traefik.enable=true"
   - "traefik.http.routers.traefik.rule=Host(`traefik.egozz.localhost`)"
   - "traefik.http.routers.traefik.entrypoints=web"
   - "traefik.http.routers.traefik.service=api@internal"
   - "traefik.http.routers.traefik.middlewares=auth"
   - "traefik.http.middlewares.auth.basicauth.users=shadow:$$2a$$09$$Gdu85mxZpnSCCJV9NXuYo.Lxd9Pawk19wBTSBGNRjMTCTwFcO6npa"