version: '3'
services: 
 db :
  container_name: db
  build : 
   context: "./mysql"
   dockerfile: "Dockerfile"
  environment: 
   - MYSQL_ROOT_PASSWORD=mindfire
   - MYSQL_DATABASE=egozz
   - MYSQL_USER=satyamp
   - MYSQL_PASSWORD=allow
  labels:
   - "traefik.enable=true"
   - "traefik.http.routers.db.rule=Host(`db.egozz.localhost`)"
   - "traefik.http.routers.db.entrypoints=web"
  volumes: 
   - ./mysql/db:/var/lib/mysql
 ui:
  container_name: ui
  build:
   context: "./ui"
   dockerfile: "Dockerfile"
  volumes: 
   - "./ui/uiresource:/app"
  labels:
   - "traefik.enable=true"
   - "traefik.http.routers.ui.rule=Host(`egozz.localhost`)"
   - "traefik.http.routers.ui.entrypoints=web"
 api:
  container_name: api
  build:
   context: "./api"
   dockerfile: "Dockerfile"
  env_file: "./credentials.env"
  ports:
   - "8055:8055"
  volumes:
    - "./api/apiresource:/api"
    - "./api/maven_repo:/root/.m2/repository"
  depends_on :
   - db
  restart: always
  labels:
   - "traefik.enable=true"
   - "traefik.http.routers.api.rule=Host(`api.egozz.localhost`)"
   - "traefik.http.routers.api.entrypoints=web"
 phpmyadmin :
  container_name: phpmyadmin
  image: phpmyadmin/phpmyadmin
  ports : 
   - "8051:80"
  environment:
   - PMA_HOST=db
  links:
   - db
  labels:
   - "traefik.enable=true"
   - "traefik.http.routers.dbadmin.rule=Host(`admin.egozz.localhost`)"
   - "traefik.http.routers.dbadmin.entrypoints=web"
 traefik:
  container_name: traefik
  image: traefik:2.1.3
  command: 
   - "--api.insecure=true"
   - "--providers.docker=true"
   - "--providers.docker.exposedbydefault=false"
   - "--entrypoints.web.address=:80"
  ports:
   - "8080:8080"
   - "80:80"
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock:ro"
  labels:
   - "traefik.enable=true"
   - "traefik.http.routers.traefik.rule=Host(`traefik.egozz.localhost`)"
   - "traefik.http.routers.traefik.entrypoints=web"
   - "traefik.http.routers.traefik.service=api@internal"
   - "traefik.http.routers.traefik.middlewares=auth"
   - "traefik.http.middlewares.auth.basicauth.users=shadow:$$2a$$09$$Gdu85mxZpnSCCJV9NXuYo.Lxd9Pawk19wBTSBGNRjMTCTwFcO6npa"