FROM node:13.7 as angularDev

RUN npm install -g @angular/cli@8.3.20

WORKDIR /app

COPY ./uiresource /app

RUN ./init.sh

FROM nginx:1.13.3-alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=angularDev /app/dist/egoz /usr/share/nginx/html

COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx","-g","daemon off;"]